### ISSUE TITLE
Component Request: CTA with background image and overlay

### ISSUE THREAD

**Issue by jeffpreussner** [praveenjuge/mynaui#4]
**Name:**
Name of the component

**Category:**

- [ ] Basic Element
- [x] Marketing
- [ ] Application
- [x] Ecommerce

**Describe the component:**
CTA Components with background image and overlay options https://www.relume.io/react/components?categories=cta-sections

**Comment by praveenjuge** [comment]
Added here: https://mynaui.com/components/call-to-action
