### ISSUE TITLE
Component Request: Container with column options

### ISSUE THREAD

**Issue by jeffpreussner** [praveenjuge/mynaui#5]
**Name:**
Name of the component

**Category:**

- [x] Basic Element
- [ ] Marketing
- [x] Application
- [ ] Ecommerce

**Describe the component:**
Container with column options, 25/75, 30/70, 33/33/33, 50/50, etc

**Comment by praveenjuge** [comment]
Thanks for the request!

Added here: https://mynaui.com/components/containers#multiple-columns

@jeffpreussner let me know if you have more requests, I'm currently working through the backlog and adding more components.
