### ISSUE TITLE
"=" used instead of "==="

### ISSUE THREAD

**Issue by jeffpreussner** [praveenjuge/mynaui#6]
**Describe the bug**
Design system component examples use `key =  ...` instead of `key === ...` 
`
**To Reproduce**

1. Go to design system components
2. See error in BorderRadius, Shadows, Blur

**Expected behavior**
Copying and pasting components from design system will work without error.

**Screenshots**
![Screenshot 2024-11-01 at 10 12 30 AM](https://github.com/user-attachments/assets/9a8023e7-2ef1-49dd-8eb6-4cc5c9ecfeb8)

**Comment by praveenjuge** [comment]
Thanks for raising this! 

There was a problem with the syntax highlighter, it should be fixed now!
